USE FamilyTree;
GO

CREATE TABLE Members (
    OBJECTID INT IDENTITY(1,1) PRIMARY KEY,
    FIRST_NAME NVARCHAR(256) NULL,
    LAST_NAME NVARCHAR(256) NULL,
    BIRTH_DATE DATETIME2(7) NULL,
    MOTHER INT NULL,
    FATHER INT NULL
);

