input_list = [
    'Quality of Life',
    'Transportation and Infrastructure',
    'Library',
    'Planning and Community Engagement',
    'Safety',
    'High Performing Government',
    'Economic Development',
    'Parks and Recreation',
    'Recreation Centers',
    'Salinas',
    'Water',
    '(AIA)',
    'Airport Influence Area',
    'Alisal Vibrancy Plan',
    'Fire',
    'Police',
    'Public Works',
    'Salinas Municipal Airport',
    'Survey',
    'Vision Salinas',
    'Landuse',
    'Alisal',
    'Alisal District',
    'Alternative Transportation',
    'Bench Mark',
    'Benchmark',
    'Bicycle',
    'Bike',
    'Bike Plan',
    'Bike Route',
    'Bike path',
    'Bikepath',
    'Bikeway',
    'Centerline',
    'City of Salinas Boundary',
    'Community Center',
    'Community Centers',
    'Community Development',
    'Community Services',
    'Council Districts',
    'Emergency Response',
    'FEMA',
    'Facilities',
    'Family Center',
    'Family Resource Center',
    'Federal Emergency Management Agency',
    'Fire Department',
    'Fire House',
    'Fire Station',
    'Firefighter',
    'Flood',
    'GPS',
    'GPS Control Network',
    'General Plan',
    'Half Mile',
    'Intersection Counts',
    'Intersections',
    'KPI',
    'Landmarks',
    'Monument',
    'NFHL',
    'NGS',
    'NTMP',
    'National Geodetic Survey',
    'Survey',
    'Neighborhood Vibrancy',
    'Open',
    'Open Space',
    'Park',
    'Recreation',
    'Road',
    'Roundabouts',
    'Intersections',
    'Space',
    'Speed Bumps',
    'Traffic',
    'Transportation',
    'Urban Design',
    'Walk',
    'Youth Centers',
    'Building',
    'Planning',
    'Zoning'
]

for word in sorted(input_list):
    # print(word)
    print(word.lower())