var app = {};

app.cfg = {
    /*

    The initial prompt is shown when the page is loaded. A list of categories is then printed.

    */
    INITIAL_PROMPT: 'Hello, which of the following are you interested in?',
    CATEGORIES: [
        'Airport Influence Area',
        'Alisal',
        'Alisal District',
        'Alisal Vibrancy Plan',
        'Alternative Transportation',
        'Bench Mark',
        'Benchmark',
        'Bikes',
        'Building',
        'Centerline',
        'City of Salinas Boundary',
        'Community Center',
        'Community Centers',
        'Community Development',
        'Community Services',
        'Council Districts',
        'Economic Development',
        'Emergency Response',
        'FEMA',
        'Facilities',
        'Family Center',
        'Family Resource Center',
        'Federal Emergency Management Agency',
        'Fire',
        'Fire Department',
        'Fire House',
        'Fire Station',
        'Firefighter',
        'Flood',
        'GPS',
        'GPS Control Network',
        'General Plan',
        'Half Mile',
        'High Performing Government',
        'Intersection Counts',
        'Intersections',
        'KPI',
        'Landmarks',
        'Landuse',
        'Library',
        'Map Gallery',
        'Monument',
        'NFHL',
        'NGS',
        'NTMP',
        'National Geodetic Survey',
        'Neighborhood Vibrancy',
        'Open',
        'Open Data',
        'Open Space',
        'Park',
        'Parks and Recreation',
        'Planning',
        'Planning and Community Engagement',
        'Police',
        'Public Works',
        'Quality of Life',
        'Recreation',
        'Recreation Centers',
        'Road',
        'Roundabouts',
        'Safety',
        'Salinas',
        'Salinas Municipal Airport',
        'Space',
        'Speed Bumps',
        'Storymaps',
        'Survey',
        'Traffic',
        'Transportation',
        'Transportation and Infrastructure',
        'Urban Design',
        'Vision Salinas',
        'Walk',
        'Water',
        'Youth Centers',
        'Zoning'
    ]
};